##############   æ³¨æ„:è¯¥é…ç½®æ–‡ä»¶ä¸ºmetaå†…æ ¸ä¸“ç”¨,ä¸é€‚åˆå…¶ä»–clashå†…æ ¸   #################
################# ipv6æ”¯æŒï¼š https://github.com/yangxiaoge/tvbox_cust/blob/master/clash/ipv6_set.jpg #################
##############   é…ç½®æ¥æºï¼šhttps://t.me/openclash_open/106164   #################

###############################   å»ºç«‹é”šç‚¹   #####################################
pp: &pp {type: http, interval: 43200, health-check: {enable: true, url: https://www.gstatic.com/generate_204, interval: 600, format: yaml}}    #####   è®¢é˜…é”šç‚¹   #####
pc: &pc {type: http, behavior: classical, interval: 86400, format: yaml}    #####   rule-providersé”šç‚¹   #####
pd: &pd {type: http, behavior: domain, interval: 86400, format: yaml}    #####   rule-providersé”šç‚¹   #####
pi: &pi {type: http, behavior: ipcidr, interval: 86400, format: yaml}    #####   rule-providersé”šç‚¹   #####
o1: &o1 {type: select, proxies: [ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, WARP, ğŸ’  å…¶ä»–åœ°åŒº, DIRECT]}    ######  ç­–ç•¥ç»„æç‚¹   ######
o2: &o2 {type: select, proxies: [DIRECT, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, WARP, ğŸ’  å…¶ä»–åœ°åŒº]}    ######  ç­–ç•¥ç»„æç‚¹   ######
###############################   å»ºç«‹é”šç‚¹   #####################################

########################################################################åˆ†éš”ç¬¦
# url é‡Œå¡«å†™è‡ªå·±çš„è®¢é˜…,è®¢é˜…åç§°ä¸èƒ½é‡å¤
proxy-providers:
  ç™½å«–èŠ‚ç‚¹1:    ###è®¢é˜…åç§°###
    <<: *pp
    url: "https://cdn.jsdelivr.net/gh/yangxiaoge/tvbox_cust@master/clash/Clash3.yml"

  ç™½å«–èŠ‚ç‚¹2:    ###è®¢é˜…åç§°###
    <<: *pp
    url: "https://cdn.jsdelivr.net/gh/yangxiaoge/tvbox_cust@master/clash/Clash.yml"

    

########################################################################åˆ†éš”ç¬¦

mixed-port: 7890
allow-lan: true
ipv6: true      ###æ¥å— IPv6 æµé‡
mode: Rule
log-level: debug
external-controller: 0.0.0.0:9090
secret: "123456"
find-process-mode: strict
global-client-fingerprint: chrome
profile:
  store-selected: true
  store-fake-ip: true

dns:
  enable: true
  ipv6: true      ###å¼€å¯IPV6 dnsè§£æ
  enhanced-mode: fake-ip ###Clash çš„ DNS å¤„ç†æ¨¡å¼
  fake-ip-range: 198.18.0.1/16 ###fakeip è¿‡æ»¤ï¼Œä»¥ä¸‹åœ°å€ä¸ä¼šä¸‹å‘ fakeip æ˜ å°„ç”¨äºè¿æ¥
  listen: 0.0.0.0:7874 ###DNS æœåŠ¡ç›‘å¬
  nameserver:  ###é»˜è®¤çš„åŸŸåè§£ææœåŠ¡å™¨ï¼Œå…·ä½“ï¼šhttps://wiki.metacubex.one/config/dns/#use-hosts
    - tls://223.5.5.5
    - tls://119.29.29.29
  default-nameserver: ###é»˜è®¤ DNS, ç”¨äºè§£æ DNS æœåŠ¡å™¨ çš„åŸŸå
    - 223.5.5.5
    - 114.114.114.114
    - 8.8.8.8
    - tls://223.5.5.5:853
    - https://223.5.5.5/dns-query
  proxy-server-nameserver: ###ä»£ç†èŠ‚ç‚¹åŸŸåè§£ææœåŠ¡å™¨ï¼Œä»…ç”¨äºè§£æä»£ç†èŠ‚ç‚¹çš„åŸŸå
    - https://dns.alidns.com/dns-query
    - https://dns.pub/dns-query
  nameserver-policy: ###æŒ‡å®šåŸŸåæŸ¥è¯¢çš„è§£ææœåŠ¡å™¨
    'rule-set:Bahamut':
      - 'https://dns.google/dns-query#ğŸ“½ï¸ å·´å“ˆå§†ç‰¹'
      - 'https://dns.cloudflare.com/dns-query#ğŸ“½ï¸ å·´å“ˆå§†ç‰¹'
    'rule-set:Geolocation-!cn': ###éä¸­å›½å¤§é™†çš„dnsæŸ¥è¯¢æœåŠ¡å™¨è®¾ç½® 
     - 'https://dns.google/dns-query#ğŸš€ èŠ‚ç‚¹é€‰æ‹©'
     - 'https://dns.cloudflare.com/dns-query#ğŸš€ èŠ‚ç‚¹é€‰æ‹©'

  fake-ip-filter: ###fakeip è¿‡æ»¤ï¼Œä»¥ä¸‹åœ°å€ä¸ä¼šä¸‹å‘ fakeip æ˜ å°„ç”¨äºè¿æ¥
    - "*.lan"
    - "*.localdomain"
    - "*.example"
    - "*.invalid"
    - "*.localhost"
    - "*.test"
    - "*.local"
    - "*.home.arpa"
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time-ios.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - "*.time.edu.cn"
    - "*.ntp.org.cn"
    - "+.pool.ntp.org"
    - time1.cloud.tencent.com
    - music.163.com
    - "*.music.163.com"
    - "*.126.net"
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - "*.kuwo.cn"
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - y.qq.com
    - "*.y.qq.com"
    - streamoc.music.tc.qq.com
    - mobileoc.music.tc.qq.com
    - isure.stream.qqmusic.qq.com
    - dl.stream.qqmusic.qq.com
    - aqqmusic.tc.qq.com
    - amobile.music.tc.qq.com
    - "*.xiami.com"
    - "*.music.migu.cn"
    - music.migu.cn
    - "+.msftconnecttest.com"
    - "+.msftncsi.com"
    - localhost.ptlogin2.qq.com
    - localhost.sec.qq.com
    - "+.qq.com"
    - "+.tencent.com"
    - "+.srv.nintendo.net"
    - "*.n.n.srv.nintendo.net"
    - "+.stun.playstation.net"
    - xbox.*.*.microsoft.com
    - "*.*.xboxlive.com"
    - xbox.*.microsoft.com
    - xnotify.xboxlive.com
    - "+.battlenet.com.cn"
    - "+.wotgame.cn"
    - "+.wggames.cn"
    - "+.wowsgame.cn"
    - "+.wargaming.net"
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - "+.stun.*.*"
    - "+.stun.*.*.*"
    - "+.stun.*.*.*.*"
    - "+.stun.*.*.*.*.*"
    - heartbeat.belkin.com
    - "*.linksys.com"
    - "*.linksyssmartwifi.com"
    - "*.router.asus.com"
    - mesu.apple.com
    - swscan.apple.com
    - swquery.apple.com
    - swdownload.apple.com
    - swcdn.apple.com
    - swdist.apple.com
    - lens.l.google.com
    - stun.l.google.com
    - na.b.g-tun.com
    - "+.nflxvideo.net"
    - "*.square-enix.com"
    - "*.finalfantasyxiv.com"
    - "*.ffxiv.com"
    - "*.ff14.sdo.com"
    - ff.dorado.sdo.com
    - "*.mcdn.bilivideo.cn"
    - "+.media.dssott.com"
    - shark007.net
    - Mijia Cloud
    - "+.cmbchina.com"
    - "+.cmbimg.com"
    - local.adguard.org
    - "+.sandai.net"
    - "+.n0808.com"

#####   è‡ªå»ºèŠ‚ç‚¹   #####
#ï¼ˆç™½å«–WARPï¼Œå¦‚æœæµé‡ç”¨å®Œäº†ï¼Œå¯ä»¥æœç´¢youtueç›¸å…³æ•™ç¨‹ï¼‰
proxies:
  # - name: "WARP"
  #   type: wireguard
  #   server: 162.159.195.236
  #   port: 934
  #   ip: "172.16.0.2"
  #   private-key: "2BRV6OmpaiQ1g5q3tzOJ/0cuEHUK1lYmIWZB1g+/mEs=" # è‡ªè¡Œæ›¿æ¢
  #   public-key: "bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo="   # è‡ªè¡Œæ›¿æ¢
  #   udp: true
  #   mtu: 1280
  - {name: WARP, type: wireguard, server: 162.159.195.236, port: 934, ip: 172.16.0.2, private-key: 2BRV6OmpaiQ1g5q3tzOJ/0cuEHUK1lYmIWZB1g+/mEs=, public-key: bmXOC+F1FxEMF9dyiK2H5/1SUtzH0JuVo51h2wPfgyo=, udp: true, mtu: 1280}

proxy-groups:
  - {name: ğŸš€ èŠ‚ç‚¹é€‰æ‹©, type: select, proxies: [â™»ï¸ è‡ªåŠ¨é€‰æ‹©, ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, ğŸ’  å…¶ä»–åœ°åŒº, DIRECT]}
  - {name: ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©, type: select, include-all-providers: true}
  - {name: â™»ï¸ è‡ªåŠ¨é€‰æ‹©, type: url-test, interval: 600, tolerance: 100, lazy: true, url: https://www.gstatic.com/generate_204, include-all-providers: true}
  - {name: ğŸ“² ç”µæŠ¥ä¿¡æ¯, <<: *o1}
  - {name: ğŸ“± Twitter, <<: *o1}
  - {name: ğŸ’¬ OpenAi, <<: *o1}
  - {name: ğŸ¬ æ²¹ç®¡è§†é¢‘, <<: *o1}
  - {name: ğŸ¥ å¥ˆé£è§†é¢‘, <<: *o1}
  - {name: ğŸ“½ï¸ å·´å“ˆå§†ç‰¹, type: select, proxies: [ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©]}
  - {name: ğŸ“º å“”å“©å“”å“©, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹]}
  - {name: ğŸŒ å›½å¤–åª’ä½“, <<: *o1}
  - {name: ğŸŒ å›½å†…åª’ä½“, type: select, proxies: [ğŸ¯ å…¨çƒç›´è¿, ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, ğŸš€ èŠ‚ç‚¹é€‰æ‹©, ğŸ› ï¸ æ‰‹åŠ¨é€‰æ‹©]}
  - {name: ğŸ“¢ è°·æ­ŒFCM, <<: *o2}
  - {name: â“‚ï¸ å¾®è½¯æœåŠ¡, <<: *o2}
  - {name: ğŸ è‹¹æœæœåŠ¡, <<: *o2}
  - {name: ğŸ® æ¸¸æˆå¹³å°, <<: *o2}
  - {name: ğŸ”° ä¸‹è½½å¹³å°, <<: *o2}
  - {name: ğŸ¯ å…¨çƒç›´è¿, type: select, proxies: [DIRECT,REJECT]}
  - {name: ğŸƒ å¹¿å‘Šæ‹¦æˆª, type: select, proxies: [REJECT,DIRECT]}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *o2}
#åœ°åŒºç­–ç•¥ç»„
  - {name: ğŸ‡­ğŸ‡° é¦™æ¸¯èŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)æ¸¯|hk|hongkong|hong kong"}
  - {name: ğŸ‡¨ğŸ‡³ å°æ¹¾èŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)å°|tw|taiwan|tai wan"}
  - {name: ğŸ‡¸ğŸ‡¬ ç‹®åŸèŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)æ–°åŠ å¡|sg|singapore|ç‹®åŸ"}
  - {name: ğŸ‡¯ğŸ‡µ æ—¥æœ¬èŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)æ—¥|jp|japan"}
  - {name: ğŸ‡ºğŸ‡¸ ç¾å›½èŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)ç¾|us|unitedstates|united states"}
  - {name: ğŸ‡°ğŸ‡· éŸ©å›½èŠ‚ç‚¹, type: select, include-all-providers: true, filter: "(?i)éŸ©å›½|kr|korea"}
  - {name: ğŸ’  å…¶ä»–åœ°åŒº, type: select, include-all-providers: true, filter: "(?i)^(?!.*(?:ğŸ‡­ğŸ‡°|ğŸ‡¯ğŸ‡µ|ğŸ‡ºğŸ‡¸|ğŸ‡¸ğŸ‡¬|ğŸ‡¨ğŸ‡³|æ¸¯|hk|hongkong|å°|tw|taiwan|æ—¥|jp|japan|æ–°|sg|singapore|ç¾|us|unitedstates|éŸ©|kr|korea)).*"}

rules:
  # æ³¨æ„ä»¥ä¸‹è§„åˆ™çš„å…ˆåé¡ºåºï¼Œæ˜¯ä¾æ¬¡åˆ¤æ–­åä¸­æ‰§è¡Œçš„
  - RULE-SET,LocalAreaNetwork,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Unban,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,MyDirect,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,BanEasyListChina,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanAD,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanEasyList,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,BanEasyPrivacy,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  # å¹¿å‘Šè¯¯åˆ è¿‡å¤šï¼æ²¡å¿…è¦è¿½æ±‚æè‡´å»å¹¿å‘Šï¼Œæœ‰å¼Šç«¯ï¼
  # - RULE-SET,MyAD,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  # - RULE-SET,MyForbidden,ğŸƒ å¹¿å‘Šæ‹¦æˆª
  - RULE-SET,MyProxy,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Bing,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,GFW,ğŸš€ èŠ‚ç‚¹é€‰æ‹©
  - RULE-SET,Telegram,ğŸ“² ç”µæŠ¥ä¿¡æ¯
  - RULE-SET,Twitter,ğŸ“± Twitter
  - RULE-SET,OpenAi,ğŸ’¬ OpenAi
  - RULE-SET,YouTube,ğŸ¬ æ²¹ç®¡è§†é¢‘
  - RULE-SET,Netflix,ğŸ¥ å¥ˆé£è§†é¢‘
  - RULE-SET,Bahamut,ğŸ“½ï¸ å·´å“ˆå§†ç‰¹
  - RULE-SET,ProxyMedia,ğŸŒ å›½å¤–åª’ä½“
  - RULE-SET,Category-games,ğŸ® æ¸¸æˆå¹³å°
  - RULE-SET,Bilibili,ğŸ“º å“”å“©å“”å“©
  - RULE-SET,Download,ğŸ”° ä¸‹è½½å¹³å°
  - RULE-SET,ChinaMedia,ğŸŒ å›½å†…åª’ä½“
  - RULE-SET,GoogleFCM,ğŸ“¢ è°·æ­ŒFCM
  - RULE-SET,Microsoft,â“‚ï¸ å¾®è½¯æœåŠ¡
  - RULE-SET,Apple,ğŸ è‹¹æœæœåŠ¡
  - RULE-SET,Geosite_cn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Geosite_private,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaDomain,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Geoip_cn,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,Geoip_private,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaCompanyIp,ğŸ¯ å…¨çƒç›´è¿
  - RULE-SET,ChinaIp,ğŸ¯ å…¨çƒç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

rule-providers:
  Geolocation-!cn:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/geolocation-!cn.yaml"  
  LocalAreaNetwork:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/LocalAreaNetwork.yaml"
  Unban:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/UnBan.yaml" 
  BanEasyListChina:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyListChina.yaml"
  BanAD:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanAD.yaml"
  BanEasyList:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyList.yaml"
  BanEasyPrivacy:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/BanEasyPrivacy.yaml"
  GFW:
    <<: *pd
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/gfw.txt"
  Google:
    <<: *pc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Google/Google.yaml"
  Telegram:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Telegram.yaml"
  Twitter:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Twitter.yaml"
  OpenAi:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/OpenAi.yaml"
  YouTube:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/YouTube.yaml"
  Netflix:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Netflix.yaml"
  Bahamut:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bahamut.yaml"
  ProxyMedia:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ProxyMedia.yaml"
  Category-games:
    <<: *pc
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/category-games.yaml"
  Bilibili:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Bilibili.yaml" 
  Download:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Download.yaml"
  ChinaMedia:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaMedia.yaml"   
  GoogleFCM:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/GoogleFCM.yaml"  
  Bing:
    <<: *pc
    url: "https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Bing/Bing.yaml"
  Microsoft:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Microsoft.yaml"
  Apple:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/Ruleset/Apple.yaml"
  Geosite_cn:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/cn.yaml"
  Geosite_private:
    <<: *pd
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/private.yaml"
  ChinaDomain:
    <<: *pc
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaDomain.yaml"
  Geoip_cn:
    <<: *pi
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/cn.yaml"
  Geoip_private:
    <<: *pi
    url: "https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geoip/private.yaml"
  ChinaCompanyIp:
    <<: *pi
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaCompanyIp.yaml"
  ChinaIp:
    <<: *pi
    url: "https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Providers/ChinaIp.yaml"
  ##############   è‡ªå®šä¹‰è§„åˆ™   #################
  MyAD:
    <<: *pd
    # url: "https://cdn.jsdelivr.net/gh/yangxiaoge/adblockfilters@main/rules/adblockfilters.txt"
    url: "https://cdn.jsdelivr.net/gh/Loyalsoldier/clash-rules@release/reject.txt"
  MyProxy:
    <<: *pd
    url: "https://github.com/yangxiaoge/tvbox_cust/raw/master/clash/custRule/myProxy.yaml"
  #ä¾‹å¦‚ä¸€äº›æˆäººç½‘ç«™~ 
  MyForbidden:
    <<: *pd
    url: "https://github.com/yangxiaoge/tvbox_cust/raw/master/clash/custRule/myForbidden.yaml"
  MyDirect:
    <<: *pd
    url: "https://github.com/yangxiaoge/tvbox_cust/raw/master/clash/custRule/myDirect.yaml"
  ##############   è‡ªå®šä¹‰è§„åˆ™   #################

